### ISSUE TITLE
RTD Programmer error with S25FS-S Family Serial flash 

### ISSUE THREAD

**Issue by bhura112** [ghent360/RTD-2660-Programmer#8]
Dear Bernard Black and ghent360,
I am using S25FS-S Family serial flash.

rtd266x_programmer/main.cpp

Line 19 in e83f32e
 static const FlashDesc FlashDevices[] = { 

in ghent360 code:
https://github.com/ghent360/RTD-2660-Programmer/blob/94a74bcd6586c71c160da4bdcc47fdff2b518b90/RTD%20Programmer/main.cpp#L21

but this SPI flash not listed in your program. Can you please tell me how can i add this device to list , i checked the datasheet some registers are differnet but maximum are same.

**Comment by ghent360** [comment]
Which part is confusing?

It is just a table with the device ID and some parameters. Just print what
device Id you are reading, then add a line to the table with the device
name, the device ID and the rest of the parameters from the datasheet.

On Sep 25, 2017 9:53 PM, "Bhura Malik" <notifications@github.com> wrote:

Dear Bernard Black and ghent360,
I am using S25FS-S Family serial flash.

rtd266x_programmer/main.cpp

Line 19 in e83f32e
static const FlashDesc FlashDevices[] = {

in ghent360 code:
https://github.com/ghent360/RTD-2660-Programmer/blob/
94a74bcd6586c71c160da4bdcc47fdff2b518b90/RTD%20Programmer/main.cpp#L21

but this SPI flash not listed in your program. Can you please tell me how
can i add this device to list , i checked the datasheet some registers are
differnet but maximum are same.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ghent360/RTD-2660-Programmer/issues/8>, or mute the
thread

**Comment by bhura112** [comment]
http://www.mouser.com/ds/2/380/S25FS-S_00-271247.pdf
page - 137
i couldn't understand how can i read this device jedec Id
can you please help me out

**Comment by static-void** [comment]
I have answered this here: https://github.com/static-void/rtd266x_programmer/issues/2

@ghent360 don't know if you've seen my code previously, I modified yours to use the I2C on the VGA port of Linux machines (so on my board I can use a standard VGA cable). It's based on your code - thank you.

**Comment by bhura112** [comment]
**I modified yours to use the I2C on the VGA port of Linux machines (so on my board I can use a standard VGA cable)**. @static-void 
 
I am using normal Monitor VGA  cable,it's works or not ?
